config/routes.rb
Project::Application.routes.draw do

  devise_for :users
  resources :posts do
    resources :reports
  end

  root 'welcome#index'

  get '/welcome' => 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :reports

  validates :name, :ticker, :region, :presence => true
  validates :name, :length => {:minimum => 2}
  validates :name, :ticker, :uniqueness => {:message => "already added"}


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'nokogiri'
  require 'open-uri'

  def index
    @posts = Post.all
  end
  
  def show
    @posts = Post.find(params[:id])

    #NEWS
    #get news from Yahoo in XLM
    ticker = @posts.ticker
    url = "http://finance.yahoo.com/rss/headline?s="+ticker
    doc = Nokogiri::XML(open(url))
    #get strings of news items
    titles_hold = doc.css("item title")
    links_hold = doc.css("item link")
    descriptions_hold = doc.css("item description")
    pubDate_hold = doc.css("item pubDate")
    #trim namespaces
    @titles = trim_namespace(titles_hold, "title")
    @links = trim_namespace(links_hold, "link")
    @descriptions = trim_namespace(descriptions_hold, "description")
    @pubDate = trim_namespace(pubDate_hold, "pubDate")

    #STOCK PRICE
    @price = get_data(ticker, "LastTradePriceOnly")
    @currency = get_data(ticker, "Currency")

    #RECOMENDATION
    @reports = @posts.reports.all.sort_by{|e| e[:quarter]}
    @recomendation = make_recommendation(@posts.reports.find(@reports[- 1].id), @posts.reports.find(@reports[-2].id), @price) 
    @our_price = our_price(@posts.reports.find(@reports[- 1].id), @posts.reports.find(@reports[-2].id))
  end
  
  def new
    @posts = Post.new
  end
  
  def create
    @posts = Post.new(posts_params)
    
    if @posts.save
      redirect_to posts_path, :notice => "New company was added successfully"
    else
      render "new"
    end
  end
  
  def edit
    @posts = Post.find(params[:id])
  end
  
  def update
    @posts = Post.find(params[:id])
    
    if @posts.update_attributes(posts_params)
      redirect_to posts_path, :notice => "Company information was updated successfully"
    else
      render "edit", :notice => "Company information was not updated"
    end
  end
  
  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    redirect_to posts_path, :notice => "The information was deleted"
  end
  
 
  
  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def posts_params
      params.require(:post).permit(:name, :ticker, :description, :region, :website, :active)
    end
  
  

  helper_method :our_price, :recomendation, :get_data, :trim_namespace, :make_recommendation
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1> Edit Company Information</h1>

<%= form_for @posts do |f| %>
<% if @posts.errors.any? %>
      <h2> Errors: </h2>
        <ul>
          <% @posts.errors.full_messages.each do |message|%>
            <li><%= message %> </li>
          <%end%>
        </ul>
  <%end%>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ticker %><br/>
    <%= f.text_field :ticker %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :region %><br/>
    <%= f.text_field :region %>
  </p>
  <p>
    <%= f.label :WEB %><br/>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :active %><br/>
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit "Update Information" %></p>
<%end%>

app/views/posts/index.html.erb
<% @posts.each do |post|  %>
<div class="row" id = "posts_index_div">
  <div class="col-lg-8" id="posts_index_div_nested">
    <h2 class = "h2_conmpany_name"><%= link_to post.name, post %> </h2>
    <h4 class = "h4_ticker">Ticker: <%= post.ticker %> </h4>
    <p class = "p_region">Region: <%= post.region %> </p>
  </div>
  <div class="col-lg-1 div_recomendation_color_index">
    <span><%= recomendation(post) %></span>
  </div>
  <div class="col-lg-3" id="posts_img_div_nested">
    <span class="helper"></span><%= image_tag(post.ticker+".jpg", class: "company_logo",  :alt => post.ticker) %>
  </div>
    <hr />
 </div>
 <div class = "row">
  <div class = "col-lg-12" id = "posts_div_index_edit_delete">
    <p>
      <%= link_to "Edit" , edit_post_path(post), class: "posts_a"%> |
      <%= link_to "Delete" , post, :confirm => "Are you sure?", :method => :delete, class: "posts_a"%>
    </p>
  </div>  
</div>
 <hr>
<% end %>

<div class="row" id="div_add_new">
  <p><%=link_to "Add New Company", new_post_path%></p>
</div>

app/views/posts/new.html.erb
<h1>Add New Company</h1>

  <%= form_for @posts do |f| %>
    <% if @posts.errors.any? %>
      <h2> Errors: </h2>
        <ul>
          <% @posts.errors.full_messages.each do |message|%>
            <li><%= message %> </li>
          <%end%>
        </ul>
  <%end%>

  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :ticker %><br/>
    <%= f.text_field :ticker %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :region %><br/>
    <%= f.text_field :region %>
  </p>
  <p>
    <%= f.label :WEB %><br/>
    <%= f.text_field :website %>
  </p>  
  <p>
    <%= f.label :active %><br/>
    <%= f.check_box :active %>
  </p>
  <p><%= f.submit "Submit"%></p>
<% end %>

app/views/posts/show.html.erb
  <div class = "row" >
  	<div class="col-lg-12">
		<h1><%= @posts.name%></h1>
  	</div>
  </div>
  <div class = "row" >
  	<div class="col-lg-12">
		<h2>Ticker: <%= @posts.ticker%></h2>
  	</div>
  </div>
  <hr>
  <div class = "row" >
  	<div class="col-lg-4">
  		<p>Market price: <%= @price + " " +@currency %> </p> 
  	</div>
  	<div class="col-lg-3" >
  		<p>Our price: <%= number_with_precision(@our_price, precision: 2)+ " " +@currency  %> </p> 
  	</div>
  	<div class="col-lg-5" id="div_recomendation_parent">
      <div class = "col-lg-9" id="div_recomendation">
  		  <p>Recomendation: <span><%= @recomendation %></span> </p> 
      </div>
      <div class = "col-lg-3" id="div_recomendation_color">
      </div>
  	</div>
  </div>
  <hr>
  <div class = "row">
  	<div class="col-lg-12">
  		<p><%= @posts.description%></p>
  	</div>
  	<hr>
  </div>
  <div class = "row">
	  	<div class="col-lg-4">
	  		<p>Region: <%= @posts.region%></p>
	  	</div>
	  	<div class="col-lg-4">
	  		<p>WEB: 
	 		 	<% if @posts.website.to_s.length > 0%>
	   				<%=link_to @posts.website, "http://"+@posts.website, class: "posts_a" %>
	  			<%else%>
	  				none
	  			<%end%>
			</p>
	  	</div>
	  	<div class="col-lg-4">
	  		<p><%=link_to "View reports", post_reports_path(@posts), class: "posts_a" %></p>
	  	</div>
  </div>
  <div class = "row">
		<hr>
		<h5>News</h5>
		<div id="posts_news">
			<% for i in 0..@titles.length%>
				<ul id = "ul_no_bullets">
					<li> <%= link_to(@titles[i].to_s, @links[i].to_s) %> </li>
					<li> <small><%= @descriptions[i]%></small> </li>
          <li> <small>Published on: <%= format_date(@pubDate[i])%></small> </li>
          <hr style="border-top: thin dashed grey" />
				</ul>
			<% end %>
		</div>
		<hr>
  </div>