config/routes.rb
Project::Application.routes.draw do

  devise_for :users
  resources :posts do
    resources :reports
  end

  root 'welcome#index'

  get '/welcome' => 'welcome#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :post

	after_save :calculate_fields

	private
	def calculate_fields   
	  other_assets = self.assets - self.curr_assets - self.goodwill - self.fixed_assets
      total_liabilities = self.assets - self.equity
      other_liabilities = total_liabilities - self.curr_liab - self.lt_debt
	  
	  self.update_column(:other_assets, other_assets)
      self.update_column(:total_liabilities, total_liabilities)
      self.update_column(:other_liabilities, other_liabilities)
  	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  helper ReportsHelper

	def index
    @post = Post.find(params[:post_id])
    @reports = @post.reports.all.sort_by{|e| e[:quarter]}

  end
  
  def new
    @post = Post.find(params[:post_id])
    @report = @post.reports.build
  end
  
  def create
    @post = Post.find(params[:post_id])
    @report = @post.reports.build(reports_params)
    
    if @report.save
      redirect_to post_reports_path, :notice => "New report was added successfully"
    else
      render "new"
    end
  end
  
  def edit
    @post = Post.find(params[:post_id])
    @report = @post.reports.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:post_id])
    @report = @post.reports.find(params[:id])
    
    if @report.update_attributes(reports_params)
      redirect_to post_reports_path, :notice => "Report information was updated successfully"
    else
      render "edit", :notice => "Report information was not updated"
    end

    
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @report = @post.reports.find(params[:id])
    @report.destroy
    redirect_to post_reports_path, :notice => "The report was deleted"
  end
  
 

  
  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def reports_params
      params.require(:report).permit(:quarter, :date_of_report, :units, :shares_outstanding, :high_price, :low_price, :percent_of_gov_income, :revenue, :opp_exp, 
        :ga_exp, :rent, :depreciation, :interest_exp, :tax, :net_income, :tax_rate, :assets, :cash, :curr_assets, :goodwill, :fixed_assets, :curr_liab, :curr_debt, 
        :lt_debt, :equity)
    end

    helper_method :our_price
end

app/helpers/reports_helper.rb
module ReportsHelper

	def if_na(number)
		if number == 0.00
			number = "NA"
		else
			number = number_to_percentage(number, precision: 2)
		end
	end

end

app/views/reports/_bs.html.erb
		<tr>
			<td><h5>Balance Sheet</h5></td>
			<% @reports.each do |r|%>
            	<td></td>
          	<%end%>
		</tr>

		<tr>
			<td>Total assets </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.assets) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Cash </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.cash) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Current assets </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.curr_assets) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Goodwill</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.goodwill) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Fixed assets</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.fixed_assets) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Other assets</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.other_assets) %> </td>
          	<%end%>
		</tr>
		<%= render :partial => "seperate"%>

		<tr>
			<td>Total liabilities and equity</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.assets) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Current debt </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.curr_debt) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Current liabilities </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.curr_liab) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Long term debt </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.lt_debt) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Other liabilities </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.other_liabilities)%> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Total liabilities </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.total_liabilities) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Equity </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.equity) %> </td>
          	<%end%>
		</tr>

app/views/reports/_form.html.erb
<%= form_for [@post, @report] do |f| %>
    <% if @report.errors.any? %>
      <h2> Errors: </h2>
        <ul>
          <% @report.errors.full_messages.each do |message|%>
            <li><%= message %> </li>
          <%end%>
        </ul>
  <%end%>
  <p>
  <%= f.label "Name: " %>
  <%= f.label @report.post.name %><br/>
  </p>
  <p>
    <%= f.label "Qurter" %><br/>
    <%= f.text_field :quarter %>
  </p>
  <p>
    <%= f.label "Date of report" %><br/>
    <%= f.date_field :date_of_report %>
  </p>
  <p>
    <%= f.label "Number of units" %><br/>
    <%= f.text_field :units %>
  </p>
  <p>
    <%= f.label "Number of shares outstanding" %><br/>
    <%= f.text_field :shares_outstanding %>
  </p>
    <p>
    <%= f.label "Highest price" %><br/>
    <%= f.text_field :high_price %>
  </p>
  <p>
    <%= f.label "Lowest price" %><br/>
    <%= f.text_field :low_price %>
  </p>  
  <p>
    <%= f.label "Percent of government income" %><br/>
    <%= f.text_field :percent_of_gov_income %> %
  </p>
  <hr>
 <p>
    <%= f.label "Revenue" %><br/>
    <%= f.text_field :revenue %> 
  </p>
 <p>
    <%= f.label "Opperational expenses" %><br/>
    <%= f.text_field :opp_exp %> 
  </p>
   <p>
    <%= f.label "GA expenses" %><br/>
    <%= f.text_field :ga_exp %> 
  </p>
   <p>
    <%= f.label "Rent" %><br/>
    <%= f.text_field :rent %> 
  </p>
   <p>
    <%= f.label "Depreciation" %><br/>
    <%= f.text_field :depreciation %> 
  </p>
     <p>
    <%= f.label "Interest expenses" %><br/>
    <%= f.text_field :interest_exp %> 
  </p>
   <p>
    <%= f.label "Tax" %><br/>
    <%= f.text_field :tax %> 
  </p>
   <p>
    <%= f.label "Net Income" %><br/>
    <%= f.text_field :net_income %> 
  </p>
   <p>
    <%= f.label "Tax rate" %><br/>
    <%= f.text_field :tax_rate %> %
  </p>
  <hr>
 <p>
    <%= f.label "Total assets" %><br/>
    <%= f.text_field :assets %> 
  </p>
   <p>
    <%= f.label "Cash" %><br/>
    <%= f.text_field :cash %> 
  </p>
   <p>
    <%= f.label "Current assets" %><br/>
    <%= f.text_field :curr_assets %> 
  </p>
   <p>
    <%= f.label "Goodwill" %><br/>
    <%= f.text_field :goodwill %> 
  </p>
   <p>
    <%= f.label "Fixed assets" %><br/>
    <%= f.text_field :fixed_assets %> 
  </p>
   <p>
    <%= f.label "Current liabilities" %><br/>
    <%= f.text_field :curr_liab %> 
  </p>
   <p>
    <%= f.label "Current debt" %><br/>
    <%= f.text_field :curr_debt %> 
  </p>
   <p>
    <%= f.label "Long term debt" %><br/>
    <%= f.text_field :lt_debt %> 
  </p>
   <p>
    <%= f.label "Equity" %><br/>
    <%= f.text_field :equity %> 
  </p>
  <p><%= f.submit "Submit"%></p>
  <%end%>

app/views/reports/_general.html.erb
		<tr>
			<th>Quarter</th>
			<% @reports.each do |r|%>
            	<th class = "allign_center"><%= r.quarter %> </th>
          	<%end%>
		</tr>

		<tr>
			<td>Date of report </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= r.date_of_report %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Units </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.units) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Shares outstanding </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.shares_outstanding) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>High price </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_precision(r.high_price, precision: 2) %> </td>
          	<%end%>
		</tr>	
		<tr>
			<td>Low price </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_precision(r.low_price, precision: 2) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Revenue percent of government income</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= if_na(r.percent_of_gov_income) %> </td>
          	<%end%>
		</tr>

app/views/reports/_our_model.html.erb
		<tr>
			<td><h5>Our model</h5></td>
			<% @reports.each do |r|%>
            	<td></td>
          	<%end%>
		</tr>

		<tr>
			<td>Calculated price </td>
				<% @reports.each_with_index do |r, i|%>
					<%if i == 0 %>
						<td class = "allign_right"><%= "NA" %> </td>
					<% else %>
						<td class = "allign_right">
							<%= number_with_precision(our_price(r, @reports[i-1]), precision: 2)%>
						</td>
					<% end %>
				<% end %>
		</tr>
	

app/views/reports/_pl.html.erb
		<tr>
			<td><h5>P&ampL Statement</h5></td>
			<% @reports.each do |r|%>
            	<td></td>
          	<%end%>
		</tr>

		<tr>
			<td>Revenue </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.revenue) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Opperating expenses </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.opp_exp) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>GA expenses</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.ga_exp) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Rent </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.rent) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Depreciation </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.depreciation) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Interest expenses </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.interest_exp) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Tax </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.tax) %> </td>
          	<%end%>
		</tr>
		<tr>
			<td>Net income</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.net_income) %> </td>
          	<%end%>
		</tr>
		<%= render :partial => "seperate"%>

		<!-- EBITDA IS CALCULATED, NOT FROM MODEL-->
		<tr>
			<td>EBITDA</td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_with_delimiter(r.revenue - r.opp_exp - r.ga_exp - r.rent) %> </td>
          	<%end%>
		</tr>
			
		<tr>
			<td>Tax rate </td>
			<% @reports.each do |r|%>
            	<td class = "allign_right"><%= number_to_percentage(r.tax_rate, precision: 2) %> </td>
          	<%end%>
		</tr>
	

app/views/reports/_seperate.html.erb
<!-- Empty line table seperator-->
		<tr>
			<td> </td>
			<% @reports.each do |r|%>
            	<td></td>
          	<%end%>
		</tr>

app/views/reports/_update.html.erb
		<tr>
			<td><h5>Update</h5></td>
			<% @reports.each do |r|%>
            	<td></td>
          	<%end%>
		</tr>

		<tr>
			<td><small>Created at</small> </td>
			<% @reports.each do |r|%>
            	<td class = "allign_center"><small><%= r.created_at %></small> </td>
          	<%end%>
		</tr>
		<tr>
			<td><small>Last updated at</small> </td>
			<% @reports.each do |r|%>
            	<td class = "allign_center"><small><%= r.updated_at %></small> </td>
          	<%end%>
		</tr>
		<tr>
			<td><small>Edit report</small> </td>
			<% @reports.each do |r|%>
            	<td class = "allign_center"><small><%= link_to "Edit", edit_post_report_path(@post, r) %></small></td>
          	<%end%>
		</tr>
		<tr>
			<td><small>Delete report</small> </td>
			<% @reports.each do |r|%>
            	<td class = "allign_center"><small><%= link_to "Delete report", [@post, r], :method => :delete, :confirm => "Are you sure?" %></small></td>
          	<%end%>
		</tr>

app/views/reports/edit.html.erb
<h1> Edit Report</h1>

<%= render :partial => 'form' %>

app/views/reports/index.html.erb
<h1>Reports</h1>

<h1> <%= @post.name%> </h1>
</br>

<table class="table table-condensed">
	<tbody>
		<%= render :partial => "general"%>
		<%= render :partial => "seperate"%>

		<%= render :partial => "pl"%>
		<%= render :partial => "seperate"%>

		<%= render :partial => "bs"%>
		<%= render :partial => "seperate"%>

		<%= render :partial => "our_model"%>
		<%= render :partial => "seperate"%>

		<%= render :partial => "update"%>
	</tbody>
</table>

<div class="row" id="div_add_new">
  <p><%=link_to "Create New Report", new_post_report_path(@post) %></p>
</div>



		

app/views/reports/new.html.erb
<h1>Add New Report</h1>

  <%= render :partial => 'form' %>

app/views/reports/show.html.erb
<table class="table table-condensed">
	<h1> <%= @post.name%> </h1>

	<thead>
		<tr>
			<th>Quarter</th>
			<th><%= @report.quarter%></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Date of report </td>
			<td><%= @report.date_of_report%></td>
		</tr>	
		<tr>
			<td>Date of report </td>
			<td><%= @report.date_of_report%></td>
		</tr>	
		<tr>
			<td>Units </td>
			<td><%= @report.units%></td>
		</tr>	
		<tr>
			<td>Shares outstanding</td>
			<td><%= @report.shares_outstanding%></td>
		</tr>	
		<tr>
			<td>High price</td>
			<td><%= @report.high_price%></td>
		</tr>	
		<tr>
			<td>Low price </td>
			<td><%= @report.low_price%></td>
		</tr>	
		<tr>
			<td>Revenue percent of government income</td>
			<td><%= @report.percent_of_gov_income%></td>
		</tr>
		<tr>
			<td>Revenue </td>
			<td><%= @report.revenue%></td>
		</tr>
		<tr>
			<td>Opperating expense </td>
			<td><%= @report.opp_exp%></td>
		</tr>
		<tr>
			<td>GA expense</td>
			<td><%= @report.ga_exp%></td>
		</tr>
		<tr>
			<td>Rent </td>
			<td><%= @report.rent%></td>
		</tr>
		<tr>
			<td>Depreciation</td>
			<td><%= @report.depreciation%></td>
		</tr>
		<tr>
			<td>Tax</td>
			<td><%= @report.tax%></td>
		</tr>
		<tr>
			<td>Net income</td>
			<td><%= @report.net_income%></td>
		</tr>
		<tr>
			<td>Tax rate</td>
			<td><%= @report.tax_rate%></td>
		</tr>
		<tr>
			<td>Total assets</td>
			<td><%= @report.assets%></td>
		</tr>
		<tr>
			<td>Cash</td>
			<td><%= @report.cash%></td>
		</tr>
		<tr>
			<td>Current assets</td>
			<td><%= @report.curr_assets%></td>
		</tr>
		<tr>
			<td>Goodwill</td>
			<td><%= @report.goodwill%></td>
		</tr>
		<tr>
			<td>Fixed assets</td>
			<td><%= @report.fixed_assets%></td>
		</tr>
		<tr>
			<td>Current liabilities</td>
			<td><%= @report.curr_liab%></td>
		</tr>
		<tr>
			<td>Long term debt</td>
			<td><%= @report.lt_debt%></td>
		</tr>
		<tr>
			<td>Equity</td>
			<td><%= @report.equity%></td>
		</tr>
	</tbody>

</table>
<small><%= @report.created_at %> </small>


  